### ISSUE TITLE
vue-play doesn't work with projects generated with vue-cli

### ISSUE THREAD

**Issue by weiying-chen** [vue-play/vue-play#68]
Steps:

1. Install vue-cli and do `vue init webpack play-test` (and do `npm install`)
2. Install vue-play: `npm install -D vue-play vue-play-cli`
3. Add vue-play to `package.json`: `"play": "vue-play start ./src/play --webpack-config ./build/webpack.dev.conf.js"`
4. run vue-play: `npm run play`

You'll see a long error like:

```
ERROR in   TypeError: Cannot read property '0' of undefined

  - ExternalModuleFactoryPlugin.js:19
    [play-test]/[webpack]/lib/ExternalModuleFactoryPlugin.js:19:40

(...)
```

**Comment by sky790312** [comment]
I have the same problem...
I try to set up by manual but not work.
Then I try this post:
https://dweldon.silvrback.com/vue-play
Still can't work. Is that any issue with new vue-cli version ..?

**Comment by jason90929** [comment]
+1

**Comment by dweldon** [comment]
See #44 for a related discussion.

@sky790312 I haven't updated the article yet. Please see my updated directions here:

https://gist.github.com/dweldon/b6ab44b4f53ffdfad3a77b3157f0833c

**Comment by sky790312** [comment]
I still face some problem about webpack setting.

```
/Users/kevin.hu/Documents/vreditor/node_modules/webpack/lib/webpack.js:19
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
   Details:
    * configuration.entry['babel-polyfill'] should be a string.
    * configuration.entry['babel-polyfill'] should NOT have duplicate items (items ## 0 and 1 are identical) ({
        "keyword": "uniqueItems",
        "dataPath": ".entry['babel-polyfill']",
        "schemaPath": "#/definitions/common.nonEmptyArrayOfUniqueStringValues/uniqueItems",
        "params": {
          "i": 1,
          "j": 0
        },
        "message": "should NOT have duplicate items (items ## 0 and 1 are identical)",
        "schema": true,
        "parentSchema": {
          "items": {
            "minLength": 1,
            "type": "string"
          },
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        },
        "data": [
          "./build/dev-client",
          "./build/dev-client",
          "babel-polyfill"
        ]
      }).
      [non-empty string]
    * configuration.entry['babel-polyfill'] should be one of these:
      non-empty string | [non-empty string]
    * configuration.entry should be a string.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      function returning an entry object or a promise..
    at webpack (/Users/kevin.hu/Documents/vreditor/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (/Users/kevin.hu/Documents/vreditor/build/dev-server.js:35:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

I have try with webpack 1, it works.
But it doesn't work in webpack2.

following is my project setting which generate by vue-cli

    "vue": "^2.4.2",
    "webpack": "^2.3.3",
node version over 4 with the latest vue-cli version
Any idea..?

**Comment by sky790312** [comment]
I can run it! Thanks @dweldon !

**Comment by sky790312** [comment]
@dweldon 
Now I face some problem with css preprocessor.
I have import global.styl in my project. How do I use it in vue play ..?

**Comment by dweldon** [comment]
@sky790312 You can import your global styles from `src/play/index.js`. This is shown in step 3 where I do: `import 'css';` - I actually have a `src/css/index.js` which then imports all of my stylus files.

**Comment by sky790312** [comment]
@dweldon  You mean import stylus files into that index.js file? How do you do that?

Following is my project structure. How do I use it?
https://i.stack.imgur.com/Lkvve.png

**Comment by dweldon** [comment]
@sky790312 It's exactly what it sounds like. Webpack is magic. My `src/css/index.js` looks like this:

```js
import './base.styl';
import './forms.styl';
import './tooltips.styl';
```

If you want all of your styl files included you could add a file like: `src/assets/css/index.js`:

```js
import ./buttons.styl
import ./fonts.styl
import ./global.styl
...
```

If you only want `global.styl` you could import that directly from your `src/play/index.js`.

**Comment by sky790312** [comment]
@dweldon I can run 5000 port now, but I still face some problem as :

`Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAKD5ABIAAAABjrQAAAAAAACfoAAAAVkAAAKCAAAAA…mFlx52L/Hg0KNrUdBzxUtnxwVGtpuQjwMjvPeMMO8ZD8s9D4CtrqN//S9M2ek/FckP9vfjlA==' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.`

Is there something wrong with my webpack.play.config setting..?

My global.stylus has:

```
@import url('../node_modules/bootstrap/dist/css/bootstrap.min.css')
@import url('../node_modules/font-awesome/css/font-awesome.min.css')
@import './variables.styl'
@import './fonts.styl'
@import './buttons.styl'
@import './primary-theme.styl'
@import './info-theme.styl'
```

**Comment by sky790312** [comment]
@dweldon I also facing the problem with i18n, my components is combine with vue-18n...
I use like this:

```
import { play } from 'vue-play'
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import IModal2 from '../../src/components/IModal2'

Vue.component('i-modal-2', IModal2)
Vue.use(VueI18n)
```

but it still can't understand $t(xxx) in my component..
